import "../lib/styles/globals.css";

import type { Metadata } from "next";
import { MockProvider } from "@/mocks/MockProvider";
import React from "react";
import { cn } from "@/lib/utils/cn";
import localFont from "next/font/local";

const suit = localFont({
  src: "./fonts/SUIT-Variable-woff2/SUIT-Variable.woff2",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html>
      <body className={cn("min-h-dvh", suit.className)}>
        <MockProvider />
        {children}
      </body>
    </html>
  );
}
