import "../../lib/styles/globals.css";

import type { Metadata } from "next";
import React from "react";
import { cn } from "../../lib/utils/cn";
import { dir } from "i18next";
import i18nConfig from "../../../i18nConfig";
import localFont from "next/font/local";

const suit = localFont({
  src: "../fonts/SUIT-Variable-woff2/SUIT-Variable.woff2",
  display: "swap",
});

export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={locale} dir={dir(locale)}>
      <body className={cn("min-h-dvh", suit.className)}>{children}</body>
    </html>
  );
}
